export const TEXTSTATISTICS = 'TEXTSTATISTICS'
export const CURRICULUMSTATISTICS = 'CURRICULUMSTATISTICS'
export const LECTURERSTATISTICS = 'LECTURERSTATISTICS'
export const USERSTATISTICS = 'USERSTATISTICS'
